server {
    listen       80;
    server_name  localhost;
    root         /usr/share/nginx/html;
    index        index.html;

    # SPA：/editor 等路径刷新不 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /vendor/ {
        try_files $uri =404;
    }
}
